### ISSUE TITLE
Add WhisperTokenizerFast

### ISSUE THREAD

**Issue by egorsmkv** [egorsmkv/optimized-whisper#2]
```
tokenizer = WhisperTokenizerFast.from_pretrained(model_id, language=language)
processor = WhisperProcessor.from_pretrained(model_id, tokenizer=tokenizer)
```

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by egorsmkv** [comment]
**WhisperTokenizer**:
> 3.29 s ± 882 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**WhisperTokenizerFast**:
> 50.6 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Colab: https://colab.research.google.com/drive/1Wtwm5nyAgIP093XkTkgEevKusvsboEAZ?usp=sharing
